services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: grocery
      POSTGRES_USER: grocery_user
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://grocery_user:root@db:5432/grocery
      SECRET_KEY: dev-secret-change-later
    depends_on:
      - db

volumes:
  postgres_data:
